### ISSUE TITLE
fibjs 文档翻译计划

### ISSUE THREAD

**Issue by xicilion** [xicilion/fibjs_docs#2]
## 翻译目的
为方便国际友人阅读和学习，传播 fibjs，需提供英文版文档。

## 翻译方法：
直接翻译 src 内 *.idl 和 *.dox 文件注释。

## 翻译流程：
1. 在此处评论认领翻译文件
2. fork 此项目
3. 本地翻译并提交
4. 校验后合并到主项目

## 文档生成
在 src 目录运行 doxygen。

##  翻译计划
* @lingyi  [已提交] fibjs_docs/src/pages/*
* @alexandtang [已提交] fibjs_docs/src/[A-D].*idl
* @classicemi [已提交] fibjs_docs/src/[E-H].*idl
* @Unknwon [已提交 I-L] fibjs_docs/src/[I-Zi-z].*idl，预计完成时间2014/11/09
* @IanZhao [规划中] fibjs_docs/src/[a-h].*idl

**Comment by xicilion** [comment]
@IanZhao 有金簪·进展吗？要不要把部分工作转交给其他同学？

**Comment by IanZhao** [comment]
@xicilion 我之前领了a-z的，后来好像@unknown 翻译了后面一部分。但是不清楚具体是哪些。。

**Comment by xicilion** [comment]
@IanZhao [规划中] fibjs_docs/src/[a-h].*idl
你按照这个翻吧。

**Comment by xicilion** [comment]
此项目关闭，转由公司同事全职维护。
